version: '3.8'

services:
  # Performance Optimizer Service
  performance-optimizer:
    build:
      context: ./docker/performance-optimizer
      dockerfile: Dockerfile
    container_name: performance-optimizer
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - TARGET_LOAD_TIME=2.5
      - TARGET_BUNDLE_SIZE=400
      - IMAGE_QUALITY=85
      - ENABLE_COMPRESSION=true
      - ENABLE_CACHING=true
      - ENABLE_CDN=true
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./styles:/app/styles
      - ./.next:/app/.next
      - ./performance-reports:/app/reports
    networks:
      - fix-network
    command: >
      sh -c "
        echo 'Starting Performance Optimization...' &&
        npm run optimize:images &&
        npm run optimize:bundle &&
        npm run optimize:css &&
        npm run optimize:cache &&
        npm run generate:report
      "

  # Content Readability Enhancer
  readability-enhancer:
    image: node:18-alpine
    container_name: readability-enhancer
    working_dir: /app
    environment:
      - TARGET_SCORE=100
      - FLESCH_KINCAID_TARGET=8
      - SENTENCE_LENGTH_MAX=20
      - PARAGRAPH_LENGTH_MAX=150
    volumes:
      - ./src:/app/src
      - ./content-reports:/app/reports
    networks:
      - fix-network
    command: >
      sh -c "
        npm install textstat syllable flesch flesch-kincaid &&
        node /app/enhance-readability.js
      "

  # Logo Display Fixer
  logo-fixer:
    image: node:18-alpine
    container_name: logo-fixer
    working_dir: /app
    environment:
      - FIX_HEADER_LOGOS=true
      - FIX_FOOTER_LOGOS=true
      - OPTIMIZE_LOGO_LOADING=true
    volumes:
      - ./src/components:/app/components
      - ./public/logos:/app/logos
    networks:
      - fix-network
    command: >
      sh -c "
        echo 'Fixing logo display issues...' &&
        node /app/fix-logo-display.js
      "

  # E.E.A.T. Content Generator
  eeat-content-generator:
    build:
      context: ./docker/eeat-generator
      dockerfile: Dockerfile
    container_name: eeat-generator
    ports:
      - "5001:5001"
    environment:
      - GENERATE_AUTHOR_BIOS=true
      - GENERATE_CASE_STUDIES=true
      - GENERATE_TESTIMONIALS=true
      - GENERATE_CERTIFICATIONS=true
      - GENERATE_AWARDS=true
      - BRAND_VALUE=2500000000
    volumes:
      - ./src/content/eeat:/app/content
      - ./public/case-studies:/app/case-studies
      - ./eeat-reports:/app/reports
    networks:
      - fix-network

  # SEO AI Optimizer
  seo-ai-optimizer:
    build:
      context: ./docker/seo-optimizer
      dockerfile: Dockerfile
    container_name: seo-optimizer
    ports:
      - "5002:5002"
    environment:
      - ENABLE_AI_SEO=true
      - TARGET_DA=80
      - TARGET_DR=75
      - SCHEMA_MARKUP=comprehensive
      - META_OPTIMIZATION=aggressive
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./seo-reports:/app/reports
    networks:
      - fix-network

  # Backlink Authority Builder
  backlink-builder:
    image: node:18-alpine
    container_name: backlink-builder
    working_dir: /app
    environment:
      - BUILD_AUTHORITY_LINKS=true
      - COMPETITOR_ANALYSIS=true
      - CONTENT_SYNDICATION=true
    volumes:
      - ./src/content:/app/content
      - ./backlink-reports:/app/reports
    networks:
      - fix-network
    command: >
      sh -c "
        npm install axios cheerio &&
        node /app/build-backlinks.js
      "

  # State Persistence Fixer
  state-fixer:
    image: node:18-alpine
    container_name: state-fixer
    working_dir: /app
    environment:
      - FIX_LOCAL_STORAGE=true
      - FIX_SESSION_STORAGE=true
      - IMPLEMENT_STATE_PERSISTENCE=true
    volumes:
      - ./src:/app/src
    networks:
      - fix-network
    command: >
      sh -c "
        echo 'Fixing disappearing items issue...' &&
        node /app/fix-state-persistence.js
      "

  # Brand Presentation Builder
  brand-builder:
    build:
      context: ./docker/brand-builder
      dockerfile: Dockerfile
    container_name: brand-builder
    ports:
      - "5003:5003"
    environment:
      - BRAND_VALUE=2500000000
      - PRESENTATION_STYLE=world-class
      - ENABLE_3D_GRAPHICS=true
      - ENABLE_ANIMATIONS=true
    volumes:
      - ./src/presentation:/app/presentation
      - ./public/brand:/app/brand
    networks:
      - fix-network

  # UI/UX Deployment System
  ui-deployment:
    image: node:18-alpine
    container_name: ui-deployment
    working_dir: /app
    environment:
      - DEPLOY_PRODUCTION=false
      - VALIDATE_ACCESSIBILITY=true
      - VALIDATE_PERFORMANCE=true
      - VALIDATE_SEO=true
    volumes:
      - ./:/app
    networks:
      - fix-network
    command: >
      sh -c "
        echo 'Validating complete UI/UX system...' &&
        npm run build &&
        npm run validate:all &&
        echo 'System ready for deployment!'
      "

  # Redis Cache for Performance
  redis-cache:
    image: redis:7-alpine
    container_name: redis-performance
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - fix-network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  # Nginx for Static Asset Optimization
  nginx-optimizer:
    image: nginx:alpine
    container_name: nginx-optimizer
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - fix-network

networks:
  fix-network:
    driver: bridge

volumes:
  redis-data:
  performance-reports:
  content-reports:
  eeat-reports:
  seo-reports:
  backlink-reports: